---
title: "Homework 2"
author: Na Yun Cho
output: github_document
---

```{r}
library(tidyverse)
```

# Problem 2

# Clean the data, convert variable types
```{r}
transit_df = read.csv("./data/transit_data.csv") %>%
  janitor::clean_names() %>%
  select(c(line:entry, vending, ada)) %>%
  mutate(entry = recode(entry, 'YES' = TRUE, 'NO' = FALSE)) 

```

Short paragraph about the dataset: 



Answer 1 of the dataset: 
there are a total of `r nrow(distinct(transit_df, line)) * nrow(distinct(transit_df, station_name))` distinct stations.






# Problem 3

# Clean the data in pols-month.csv 
```{r}
pols_month = read.csv("./data/fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(mon, into = c('year', 'month', 'day'), sep = '-') %>%
  mutate(month = as.numeric(month)) %>%
  mutate(month = month.abb[month]) %>%
  mutate(year = as.integer(year)) %>%
  mutate(president = case_when(
    prez_gop == 0 ~ 'dem',
    prez_gop == 1 ~ 'gop',
    prez_gop == 2 ~ 'dem')) %>%
  select(-c(prez_gop, prez_dem, day)) %>%
  relocate(year)

```

# Clean the data in snp.csv
```{r}
snp_df = read.csv("./data/fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  separate(date, into = c('month', 'day', 'year'), sep = '/') %>%
  mutate(month = as.numeric(month)) %>%
  mutate(month = month.abb[month]) %>%
  mutate(year = as.integer(year)) %>%
  relocate(year)
```

# Clean the data in unemployment.csv
```{r}
unemployment_df = read.csv("./data/fivethirtyeight_datasets/unemployment.csv") %>%
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment") %>%
  janitor::clean_names()
  
```

# Join the datasets
```{r}
snp_pols_df = left_join(pols_month, snp_df, by = c("year", "month")) 

final_df = left_join(snp_pols_df, unemployment_df, by = c("year", "month"))
                                                  
```

